
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "config.h"

#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk-pixbuf/gdk-pixdata.h>
/* enumerations from "gdk-pixbuf-core.h" */
GType
gdk_pixbuf_alpha_mode_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GEnumValue values[] = {
            { GDK_PIXBUF_ALPHA_BILEVEL, "GDK_PIXBUF_ALPHA_BILEVEL", "bilevel" },
            { GDK_PIXBUF_ALPHA_FULL, "GDK_PIXBUF_ALPHA_FULL", "full" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_enum_register_static (g_intern_static_string ("GdkPixbufAlphaMode"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
GType
gdk_colorspace_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GEnumValue values[] = {
            { GDK_COLORSPACE_RGB, "GDK_COLORSPACE_RGB", "rgb" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_enum_register_static (g_intern_static_string ("GdkColorspace"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
GType
gdk_pixbuf_error_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GEnumValue values[] = {
            { GDK_PIXBUF_ERROR_CORRUPT_IMAGE, "GDK_PIXBUF_ERROR_CORRUPT_IMAGE", "corrupt-image" },
            { GDK_PIXBUF_ERROR_INSUFFICIENT_MEMORY, "GDK_PIXBUF_ERROR_INSUFFICIENT_MEMORY", "insufficient-memory" },
            { GDK_PIXBUF_ERROR_BAD_OPTION, "GDK_PIXBUF_ERROR_BAD_OPTION", "bad-option" },
            { GDK_PIXBUF_ERROR_UNKNOWN_TYPE, "GDK_PIXBUF_ERROR_UNKNOWN_TYPE", "unknown-type" },
            { GDK_PIXBUF_ERROR_UNSUPPORTED_OPERATION, "GDK_PIXBUF_ERROR_UNSUPPORTED_OPERATION", "unsupported-operation" },
            { GDK_PIXBUF_ERROR_FAILED, "GDK_PIXBUF_ERROR_FAILED", "failed" },
            { GDK_PIXBUF_ERROR_INCOMPLETE_ANIMATION, "GDK_PIXBUF_ERROR_INCOMPLETE_ANIMATION", "incomplete-animation" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_enum_register_static (g_intern_static_string ("GdkPixbufError"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
/* enumerations from "gdk-pixbuf-transform.h" */
GType
gdk_interp_type_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GEnumValue values[] = {
            { GDK_INTERP_NEAREST, "GDK_INTERP_NEAREST", "nearest" },
            { GDK_INTERP_TILES, "GDK_INTERP_TILES", "tiles" },
            { GDK_INTERP_BILINEAR, "GDK_INTERP_BILINEAR", "bilinear" },
            { GDK_INTERP_HYPER, "GDK_INTERP_HYPER", "hyper" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_enum_register_static (g_intern_static_string ("GdkInterpType"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
GType
gdk_pixbuf_rotation_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GEnumValue values[] = {
            { GDK_PIXBUF_ROTATE_NONE, "GDK_PIXBUF_ROTATE_NONE", "none" },
            { GDK_PIXBUF_ROTATE_COUNTERCLOCKWISE, "GDK_PIXBUF_ROTATE_COUNTERCLOCKWISE", "counterclockwise" },
            { GDK_PIXBUF_ROTATE_UPSIDEDOWN, "GDK_PIXBUF_ROTATE_UPSIDEDOWN", "upsidedown" },
            { GDK_PIXBUF_ROTATE_CLOCKWISE, "GDK_PIXBUF_ROTATE_CLOCKWISE", "clockwise" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_enum_register_static (g_intern_static_string ("GdkPixbufRotation"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
/* enumerations from "gdk-pixdata.h" */
GType
gdk_pixdata_type_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GFlagsValue values[] = {
            { GDK_PIXDATA_COLOR_TYPE_RGB, "GDK_PIXDATA_COLOR_TYPE_RGB", "color-type-rgb" },
            { GDK_PIXDATA_COLOR_TYPE_RGBA, "GDK_PIXDATA_COLOR_TYPE_RGBA", "color-type-rgba" },
            { GDK_PIXDATA_COLOR_TYPE_MASK, "GDK_PIXDATA_COLOR_TYPE_MASK", "color-type-mask" },
            { GDK_PIXDATA_SAMPLE_WIDTH_8, "GDK_PIXDATA_SAMPLE_WIDTH_8", "sample-width-8" },
            { GDK_PIXDATA_SAMPLE_WIDTH_MASK, "GDK_PIXDATA_SAMPLE_WIDTH_MASK", "sample-width-mask" },
            { GDK_PIXDATA_ENCODING_RAW, "GDK_PIXDATA_ENCODING_RAW", "encoding-raw" },
            { GDK_PIXDATA_ENCODING_RLE, "GDK_PIXDATA_ENCODING_RLE", "encoding-rle" },
            { GDK_PIXDATA_ENCODING_MASK, "GDK_PIXDATA_ENCODING_MASK", "encoding-mask" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_flags_register_static (g_intern_static_string ("GdkPixdataType"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
GType
gdk_pixdata_dump_type_get_type (void)
{
    static gsize g_define_type;

    if (g_once_init_enter (&g_define_type)) {
        static const GFlagsValue values[] = {
            { GDK_PIXDATA_DUMP_PIXDATA_STREAM, "GDK_PIXDATA_DUMP_PIXDATA_STREAM", "pixdata-stream" },
            { GDK_PIXDATA_DUMP_PIXDATA_STRUCT, "GDK_PIXDATA_DUMP_PIXDATA_STRUCT", "pixdata-struct" },
            { GDK_PIXDATA_DUMP_MACROS, "GDK_PIXDATA_DUMP_MACROS", "macros" },
            { GDK_PIXDATA_DUMP_GTYPES, "GDK_PIXDATA_DUMP_GTYPES", "gtypes" },
            { GDK_PIXDATA_DUMP_CTYPES, "GDK_PIXDATA_DUMP_CTYPES", "ctypes" },
            { GDK_PIXDATA_DUMP_STATIC, "GDK_PIXDATA_DUMP_STATIC", "static" },
            { GDK_PIXDATA_DUMP_CONST, "GDK_PIXDATA_DUMP_CONST", "const" },
            { GDK_PIXDATA_DUMP_RLE_DECODER, "GDK_PIXDATA_DUMP_RLE_DECODER", "rle-decoder" },
            { 0, NULL, NULL }
        };
        GType enum_type = g_flags_register_static (g_intern_static_string ("GdkPixdataDumpType"), values);

        g_once_init_leave (&g_define_type, enum_type);
    }
    return g_define_type;
}
/* Generated data ends here */
