#define G_MODULE_SUPPORTED 1
#define G_MODULE_IMPL G_MODULE_IMPL_DL
#define G_MODULE_SUFFIX "so"
#define G_MODULE_EXPORT
#define G_MODULE_HAVE_DLERROR 1
#define G_MODULE_NEED_USCORE 0
#define G_MODULE_BROKEN_RTLD_GLOBAL 0
#define G_MODULE_HAVE_PLT 0
