/* Generated by configure. Do not edit */
#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 42
#define PANGO_VERSION_MICRO 4
#define PANGO_BINARY_AGE 4204
#define PANGO_INTERFACE_AGE 4

#define PANGO_VERSION_STRING "1.42.4"


#endif
