-- generated by scratch/gen-nss.py; edit the generator, not this file
cflags{
	'-D XP_UNIX',
	'-D LINUX',
	'-D _GNU_SOURCE',
	'-D _REENTRANT',
	'-D NSS_USE_64',
	'-D USE_UTIL_DIRECTLY',
	'-D NSS_DISABLE_DBM',
	'-include $dir/nssconf.h',
	'-I $srcdir/lib/libpkix/include',
	'-I $srcdir/cmd/lib',
	'-I $srcdir/lib/freebl/verified/internal',
	'-I $srcdir/lib/freebl/verified/karamel/include',
	'-I $srcdir/lib/freebl/verified/karamel/include/krml/internal',
	'-I $srcdir/lib/freebl/verified/karamel/krmllib/dist/minimal',
	'-I $srcdir/lib/libpkix/pkix/certsel',
	'-I $srcdir/lib/libpkix/pkix/checker',
	'-I $srcdir/lib/libpkix/pkix/crlsel',
	'-I $srcdir/lib/libpkix/pkix/params',
	'-I $srcdir/lib/libpkix/pkix/results',
	'-I $srcdir/lib/libpkix/pkix/store',
	'-I $srcdir/lib/libpkix/pkix/top',
	'-I $srcdir/lib/libpkix/pkix/util',
	'-I $srcdir/lib/libpkix/pkix_pl_nss/module',
	'-I $srcdir/lib/libpkix/pkix_pl_nss/pki',
	'-I $srcdir/lib/libpkix/pkix_pl_nss/system',
	'-I $srcdir/lib/freebl/ecl',
	'-I $srcdir/lib/freebl/mpi',
	'-I $srcdir/lib/freebl/verified',
	'-I $srcdir/lib/freebl',
	'-I $srcdir/lib/util',
	'-I $srcdir/lib/base',
	'-I $srcdir/lib/certdb',
	'-I $srcdir/lib/certhigh',
	'-I $srcdir/lib/cryptohi',
	'-I $srcdir/lib/dev',
	'-I $srcdir/lib/pk11wrap',
	'-I $srcdir/lib/pkcs7',
	'-I $srcdir/lib/pkcs12',
	'-I $srcdir/lib/pki',
	'-I $srcdir/lib/nss',
	'-I $srcdir/lib/ssl',
	'-I $srcdir/lib/ckfw',
	'-I $srcdir/lib/ckfw/builtins',
	'-I $srcdir/lib/mozpkix/include',
	'-I $srcdir/lib/smime',
	'-I $srcdir/lib/softoken',
	'-I $srcdir/lib/crmf',
	'-isystem $builddir/pkg/nspr/include',
	'-isystem $builddir/pkg/sqlite/include',
}
pkg.hdrs = {
	copy('$outdir/include/nss', '$srcdir/lib/util', {
		'base64.h',
		'ciferfam.h',
		'eccutil.h',
		'hasht.h',
		'nssb64.h',
		'nssb64t.h',
		'nsslocks.h',
		'nssilock.h',
		'nssilckt.h',
		'nssrwlk.h',
		'nssrwlkt.h',
		'nssutil.h',
		'pkcs11.h',
		'pkcs11f.h',
		'pkcs11p.h',
		'pkcs11t.h',
		'pkcs11n.h',
		'pkcs11u.h',
		'pkcs1sig.h',
		'portreg.h',
		'secasn1.h',
		'secasn1t.h',
		'seccomon.h',
		'secder.h',
		'secdert.h',
		'secdig.h',
		'secdigt.h',
		'secitem.h',
		'secoid.h',
		'secoidt.h',
		'secport.h',
		'secerr.h',
		'utilmodt.h',
		'utilrename.h',
		'utilpars.h',
		'utilparst.h',
		'pkcs11uri.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/base', {
		'nssbaset.h',
		'nssbase.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/certdb', {
		'cert.h',
		'certt.h',
		'certdb.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/certhigh', {
		'ocsp.h',
		'ocspt.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/cryptohi', {
		'cryptohi.h',
		'cryptoht.h',
		'key.h',
		'keyhi.h',
		'keyt.h',
		'keythi.h',
		'sechash.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/pk11wrap', {
		'secmod.h',
		'secmodt.h',
		'secpkcs5.h',
		'pk11func.h',
		'pk11hpke.h',
		'pk11pub.h',
		'pk11priv.h',
		'pk11sdr.h',
		'pk11pqg.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/nss', {
		'nss.h',
	}),
	copy('$outdir/include/ssl', '$srcdir/lib/ssl', {
		'ssl.h',
		'sslt.h',
		'sslerr.h',
		'sslexp.h',
		'sslproto.h',
		'preenc.h',
	}),
	copy('$outdir/include/nss', '$srcdir/lib/freebl', {'blapit.h', 'chacha20poly1305.h', 'shsign.h'}),
	copy('$outdir/include/nss', '$srcdir/lib/freebl/ecl', {'ecl-exp.h'}),
	copy('$outdir/include/nss', '$srcdir/lib/pkcs7', {'pkcs7t.h', 'secpkcs7.h'}),
	copy('$outdir/include/nss', '$srcdir/lib/smime', {'cmsreclist.h'}),
	-- mozpkix public headers (cert verification used by PSM)
	copy('$outdir/include/mozpkix/pkix', '$srcdir/lib/mozpkix/include/pkix', {
		'Input.h', 'Result.h', 'Time.h', 'pkix.h', 'pkixc.h',
		'pkixcheck.h', 'pkixder.h', 'pkixnss.h', 'pkixtypes.h',
		'pkixutil.h',
	}),
	-- gecko includes <mozpkix/pkixtypes.h> (no pkix/ level)
	copy('$outdir/include/mozpkix', '$srcdir/lib/mozpkix/include/pkix', {
		'Input.h', 'Result.h', 'Time.h', 'pkix.h', 'pkixc.h',
		'pkixcheck.h', 'pkixder.h', 'pkixnss.h', 'pkixtypes.h',
		'pkixutil.h',
	}),
	-- public p12 headers needed by the palemoon NSS glue
	copy('$outdir/include/nss', '$srcdir/lib/pkcs12', {'pkcs12.h', 'pkcs12t.h', 'p12.h', 'p12t.h'}),
	-- PSM's nsPKCS12Blob.h includes the private p12plcy.h
	copy('$outdir/include/nss', '$srcdir/lib/pkcs12', {'p12plcy.h'}),
	copy('$outdir/include/smime', '$srcdir/lib/smime', {
		'cms.h',
		'cmst.h',
		'smime.h',
		'cmsreclist.h',
	}),
	install=true,
}
pkg.deps = {
	'$gendir/headers',
	'pkg/nspr/headers',
	'pkg/sqlite/headers',
}
local nssobjs = objects([=[
lib/base/(
		arena.c
		error.c
		errorval.c
		hashops.c
		libc.c
		tracker.c
		item.c
		utf8.c
		list.c
		hash.c
)
lib/certdb/(
		alg1485.c
		certdb.c
		certv3.c
		certxutl.c
		crl.c
		genname.c
		stanpcertdb.c
		polcyxtn.c
		secname.c
		xauthkid.c
		xbsconst.c
		xconst.c
)
lib/certhigh/(
		certhtml.c
		certreq.c
		crlv2.c
		ocsp.c
		ocspsig.c
		certhigh.c
		certvfy.c
		certvfypkix.c
		xcrldist.c
)
lib/cryptohi/(
		sechash.c
		seckey.c
		secsign.c
		secvfy.c
		dsautil.c
)
lib/dev/(
		devslot.c
		devtoken.c
		devutil.c
		ckhelper.c
)
lib/pk11wrap/(
		dev3hack.c
		pk11akey.c
		pk11auth.c
		pk11cert.c
		pk11cxt.c
		pk11err.c
		pk11hpke.c
		pk11kea.c
		pk11list.c
		pk11load.c
		pk11mech.c
		pk11merge.c
		pk11nobj.c
		pk11obj.c
		pk11pars.c
		pk11pbe.c
		pk11pk12.c
		pk11pqg.c
		pk11sdr.c
		pk11skey.c
		pk11slot.c
		pk11util.c
)
lib/pkcs7/(
		certread.c
		p7common.c
		p7create.c
		p7decode.c
		p7encode.c
		p7local.c
		secmime.c
)
lib/pkcs12/(
		p12local.c
		p12creat.c
		p12dec.c
		p12plcy.c
		p12tmpl.c
		p12e.c
		p12d.c
)
lib/pki/(
		asymmkey.c
		certificate.c
		cryptocontext.c
		symmkey.c
		trustdomain.c
		tdcache.c
		certdecode.c
		pkistore.c
		pkibase.c
		pki3hack.c
)
lib/nss/(
		nssinit.c
		nssoptions.c
		nssver.c
		utilwrap.c
)
lib/libpkix/pkix/certsel/(
		pkix_certselector.c
		pkix_comcertselparams.c
)
lib/libpkix/pkix/checker/(
		pkix_basicconstraintschecker.c
		pkix_certchainchecker.c
		pkix_crlchecker.c
		pkix_ekuchecker.c
		pkix_expirationchecker.c
		pkix_namechainingchecker.c
		pkix_nameconstraintschecker.c
		pkix_ocspchecker.c
		pkix_revocationmethod.c
		pkix_revocationchecker.c
		pkix_policychecker.c
		pkix_signaturechecker.c
		pkix_targetcertchecker.c
)
lib/libpkix/pkix/crlsel/(
		pkix_crlselector.c
		pkix_comcrlselparams.c
)
lib/libpkix/pkix/params/(
		pkix_trustanchor.c
		pkix_procparams.c
		pkix_valparams.c
		pkix_resourcelimits.c
)
lib/libpkix/pkix/results/(
		pkix_buildresult.c
		pkix_policynode.c
		pkix_valresult.c
		pkix_verifynode.c
)
lib/libpkix/pkix/store/(
		pkix_store.c
)
lib/libpkix/pkix/top/(
		pkix_validate.c
		pkix_lifecycle.c
		pkix_build.c
)
lib/libpkix/pkix/util/(
		pkix_tools.c
		pkix_error.c
		pkix_logger.c
		pkix_list.c
		pkix_errpaths.c
)
lib/libpkix/pkix_pl_nss/module/(
		pkix_pl_aiamgr.c
		pkix_pl_colcertstore.c
		pkix_pl_httpcertstore.c
		pkix_pl_httpdefaultclient.c
		pkix_pl_nsscontext.c
		pkix_pl_pk11certstore.c
		pkix_pl_socket.c
		pkix_pl_ldapcertstore.c
		pkix_pl_ldapdefaultclient.c
		pkix_pl_ldaprequest.c
		pkix_pl_ldapresponse.c
		pkix_pl_ldaptemplates.c
)
lib/libpkix/pkix_pl_nss/pki/(
		pkix_pl_basicconstraints.c
		pkix_pl_cert.c
		pkix_pl_certpolicyinfo.c
		pkix_pl_certpolicymap.c
		pkix_pl_certpolicyqualifier.c
		pkix_pl_crl.c
		pkix_pl_crldp.c
		pkix_pl_crlentry.c
		pkix_pl_date.c
		pkix_pl_generalname.c
		pkix_pl_infoaccess.c
		pkix_pl_nameconstraints.c
		pkix_pl_ocsprequest.c
		pkix_pl_ocspresponse.c
		pkix_pl_publickey.c
		pkix_pl_x500name.c
		pkix_pl_ocspcertid.c
)
lib/libpkix/pkix_pl_nss/system/(
		pkix_pl_bigint.c
		pkix_pl_bytearray.c
		pkix_pl_common.c
		pkix_pl_error.c
		pkix_pl_hashtable.c
		pkix_pl_lifecycle.c
		pkix_pl_mem.c
		pkix_pl_monitorlock.c
		pkix_pl_mutex.c
		pkix_pl_object.c
		pkix_pl_oid.c
		pkix_pl_primhash.c
		pkix_pl_rwlock.c
		pkix_pl_string.c
)
lib/ckfw/(
		crypto.c
		find.c
		hash.c
		instance.c
		mechanism.c
		mutex.c
		object.c
		session.c
		sessobj.c
		slot.c
		token.c
		wrap.c
)
]=], {'$gendir/headers', 'pkg/nspr/headers', 'pkg/sqlite/headers'})
-- builtin roots module (ckbi): 10 checked-in sources + the dev-time generated
-- certdata.c artifact (hash in certdata.sha256); emit nothing when the artifact
-- is absent so fresh clones still generate a green manifest
-- NB: io.open is CWD-relative (oasis root); pkg.dir is absolute
if io.open(pkg.dir..'/certdata.c', 'r') then
	for _, obj in ipairs(objects([=[
lib/ckfw/builtins/(
		anchor.c
		bfind.c
		binst.c
		bobject.c
		bsession.c
		bslot.c
		btoken.c
		ckbiver.c
		constants.c
)
coreconf/empty.c
]=], {'$gendir/headers', 'pkg/nspr/headers'})) do
		nssobjs[#nssobjs + 1] = obj
	end
	build('cc', '$outdir/lib/ckfw/builtins/certdata.c.o',
		{'$dir/certdata.c', '||', '$gendir/deps'})
	nssobjs[#nssobjs + 1] = '$outdir/lib/ckfw/builtins/certdata.c.o'
end
ar('libnss.a', nssobjs)
ar('libmozpkix.a', objects([[lib/mozpkix/lib/pkix/(
		pkixbuild.cpp
		pkixc.cpp
		pkixcert.cpp
		pkixcheck.cpp
		pkixder.cpp
		pkixnames.cpp
		pkixnss.cpp
		pkixocsp.cpp
		pkixresult.cpp
		pkixtime.cpp
		pkixverify.cpp
)]], {'$gendir/headers', 'pkg/nspr/headers'}))
ar('libnssutil.a', objects([=[
lib/util/(
		quickder.c
		secdig.c
		derdec.c
		derenc.c
		dersubr.c
		dertime.c
		errstrs.c
		nssb64d.c
		nssb64e.c
		nssrwlk.c
		nssilock.c
		oidstring.c
		pkcs1sig.c
		portreg.c
		secalgid.c
		secasn1d.c
		secasn1e.c
		secasn1u.c
		secitem.c
		secload.c
		secoid.c
		sectime.c
		secport.c
		templates.c
		utf8.c
		utilmod.c
		utilpars.c
		pkcs11uri.c
)]=], {'$gendir/headers', 'pkg/nspr/headers'}))
ar('libssl.a', objects([=[
lib/ssl/(
		authcert.c
		cmpcert.c
		dtls13con.c
		dtlscon.c
		prelib.c
		selfencrypt.c
		ssl3con.c
		ssl3ecc.c
		ssl3ext.c
		ssl3exthandle.c
		ssl3gthr.c
		sslauth.c
		sslbloom.c
		sslcert.c
		sslcon.c
		ssldef.c
		sslencode.c
		sslenum.c
		sslerr.c
		sslerrstrs.c
		sslgrp.c
		sslinfo.c
		sslinit.c
		sslmutex.c
		sslnonce.c
		sslprimitive.c
		sslreveal.c
		sslsecur.c
		sslsnce.c
		sslsock.c
		sslspec.c
		ssltrace.c
		sslver.c
		tls13con.c
		tls13ech.c
		tls13echv.c
		tls13exthandle.c
		tls13hashstate.c
		tls13hkdf.c
		tls13psk.c
		tls13replay.c
		tls13subcerts.c
		unix_err.c
)]=], {'$gendir/headers', 'pkg/nspr/headers'}))
ar('libsmime.a', objects([=[
lib/smime/(
		cmsarray.c
		cmsasn1.c
		cmsattr.c
		cmscinfo.c
		cmscipher.c
		cmsdecode.c
		cmsdigdata.c
		cmsdigest.c
		cmsencdata.c
		cmsencode.c
		cmsenvdata.c
		cmsmessage.c
		cmspubkey.c
		cmsrecinfo.c
		cmsreclist.c
		cmssigdata.c
		cmssiginfo.c
		cmsudf.c
		cmsutil.c
		smimemessage.c
		smimeutil.c
		smimever.c
)]=], {'$gendir/headers', 'pkg/nspr/headers'}))
ar('libcrmf.a', objects([[lib/crmf/(
		crmftmpl.c
		crmfenc.c
		crmfreq.c
		crmfpop.c
		crmfdec.c
		crmfget.c
		crmfcont.c
		cmmfasn1.c
		cmmfresp.c
		cmmfrec.c
		cmmfchal.c
		servget.c
		encutil.c
		respcli.c
		respcmn.c
		challcli.c
		asn1cmn.c
)]], {'$gendir/headers', 'pkg/nspr/headers'}))
sub('freebl.ninja', function()
	cflags{

	'-D NSS_USE_COMBA',
	'-D MP_IS_LITTLE_ENDIAN',
	}
	local fbobjs = {}
	for src in iterpaths([=[lib/freebl/(
		aeskeywrap.c
		alghmac.c
		arcfive.c
		arcfour.c
		blake2b.c
		blinit.c
		camellia.c
		chacha20poly1305.c
		cmac.c
		crypto_primitives.c
		ctr.c
		cts.c
		deprecated/alg2268.c
		deprecated/seed.c
		des.c
		desblapi.c
		det_rng.c
		dh.c
		drbg.c
		dsa.c
		ec.c
		ecdecode.c
		ecl/curve25519_64.c
		ecl/ec_naf.c
		ecl/ecl.c
		ecl/ecl_gf.c
		ecl/ecl_mult.c
		ecl/ecp_25519.c
		ecl/ecp_256.c
		ecl/ecp_256_32.c
		ecl/ecp_384.c
		ecl/ecp_521.c
		ecl/ecp_aff.c
		ecl/ecp_jac.c
		ecl/ecp_jm.c
		ecl/ecp_mont.c
		ecl/ecp_secp384r1.c
		ecl/ecp_secp521r1.c
		fipsfreebl.c
		freeblver.c
		gcm.c
		hmacct.c
		jpake.c
		ldvector.c
		md2.c
		md5.c
		mpi/mp_comba.c
		mpi/mp_gf2m.c
		mpi/mpcpucache.c
		mpi/mpi.c
		mpi/mplogic.c
		mpi/mpmontg.c
		mpi/mpprime.c
		nsslowhash.c
		pqg.c
		rawhash.c
		rijndael.c
		rsa.c
		rsapkcs.c
		secmpi.c
		sha512.c
		sha_fast.c
		shvfy.c
		sysrand.c
		tlsprfalg.c
		unix_rand.c
		unix_urandom.c
		verified/Hacl_Chacha20.c
		verified/Hacl_Chacha20Poly1305_32.c
		verified/Hacl_Curve25519_51.c
		verified/Hacl_Curve25519_64.c
		verified/Hacl_Poly1305_32.c
)]=]) do
		fbobjs[#fbobjs + 1] = compile('cc', src)
	end
	ar('libfreebl.a', fbobjs)
end)
sub('softoken.ninja', function()
	ar('libsoftokn.a', objects([=[lib/softoken/(
		fipsaudt.c
		fipstest.c
		fipstokn.c
		kbkdf.c
		lowkey.c
		lowpbe.c
		padbuf.c
		pkcs11.c
		pkcs11c.c
		pkcs11u.c
		sdb.c
		sftkdb.c
		sftkdhverify.c
		sftkhmac.c
		sftkike.c
		sftkmessage.c
		sftkpars.c
		sftkpwd.c
		softkver.c
		tlsprf.c
		jpakesftk.c
)]=], {'$gendir/headers', 'pkg/nspr/headers', 'pkg/sqlite/headers'}))
end)

fetch 'local'
