#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_PTHREAD_H 1
#define WORDS_BIGENDIAN 0
#define HAVE_UINT64_T 1
