-- Pale Moon (Goanna) browser, shipped as OMoon.
-- Sources from the pinned app + UXP trees; the generated set under gen/ is a
-- dev-time artifact regenerated by scratch/harvest36.lua against the pm36
-- ground truth (not committed). Without it this package emits nothing, so the
-- rest of the tree still generates. Static PIE link lands at 5.1.
-- NB: io.open is CWD-relative (oasis root); iterlines()/load() resolve via
-- basedir/pkg.gendir. The guard must do the same.
if not io.open(basedir .. '/' .. pkg.gendir .. '/gen/defines.txt', 'r') then return end
cflags{
	'-D _LARGEFILE64_SOURCE',
	'-D _FILE_OFFSET_BITS=64',
	-- gecko C++ dialect (gt OS_CXXFLAGS)
	'-fno-exceptions', '-fno-rtti', '-fno-sized-deallocation',
	'-flifetime-dse=1', '-fno-strict-aliasing', '-fno-math-errno',
	'-D MOZILLA_INTERNAL_API',
	'-D IMPL_LIBXUL',
	'-D MOZILLA_CLIENT',
	'-D JS_CODEGEN_X64',
	'-D JS_PUNBOX64',
	'-D MOZ_WAYLAND',
	'-D VAR_ARRAYS',
	'-D GDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_4',
	-- string-valued config vars (autoconf.mk); the \" survives sh so the
	-- compiler sees a quoted C literal (gio LIBDIR pattern)
	[[-D OS_ARCH=\"Linux\"]],
	[[-D OS_TARGET=\"Linux\"]],
	[[-D OS_TEST=\"x86_64\"]],
	[[-D MOZ_WIDGET_TOOLKIT=\"gtk3\"]],
	[[-D MOZ_APP_NAME=\"palemoon\"]],
	[[-D MOZ_APP_DISPLAYNAME=\"OMoon\"]],
	[[-D MOZ_CHILD_PROCESS_NAME=\"plugin-container\"]],
	[[-D DLL_PREFIX=\"lib\"]],
	[[-D DLL_SUFFIX=\".so\"]],
	'-D SQLITE_MAX_LIKE_PATTERN_LENGTH=50000',
	[[-D MOZ_APP_VERSION=\"35.1.0a1\"]],
	-- gfx/2d backend (gt gfx/2d/backend.mk DEFINES)
	'-D USE_SSE2',
	'-D USE_CAIRO',
	'-D MOZ2D_HAS_MOZ_CAIRO',
	'-D MOZ_ENABLE_FREETYPE',
	'-include $dir/gen/include/mozilla/Char16.h',
	-- NB: -I $dir/gen/include is added AFTER the source dirs (end of this
	-- section) - top-level generated headers must not shadow tree headers
	'-I $srcdir',
	'-I $srcdir/palemoon',
	'-I pkg/uxp/src',
	'-include $dir/gen/include/mozilla-config.h',
	-- external dependencies (house static stack)
	'-isystem $builddir/pkg/nspr/include',
	'-isystem $builddir/pkg/nss/include',
	'-isystem $builddir/pkg/nss/include/nss',
	'-isystem $builddir/pkg/nss/include/ssl',
	'-isystem $builddir/pkg/nss/include/smime',
	-- speex: the consumer header renames the symbols to moz_speex_*
	'-isystem $builddir/pkg/icu/src/common',
	'-isystem $builddir/pkg/icu/src/i18n',
	'-isystem $builddir/pkg/sqlite/include',
	'-isystem $builddir/pkg/zlib/include',
	'-isystem $builddir/pkg/libpng/include',
	'-isystem $builddir/pkg/freetype/include',
	'-isystem $builddir/pkg/fontconfig/include',
	'-isystem $builddir/pkg/pixman/include',
	'-isystem $builddir/pkg/cairo/include',
	'-isystem $builddir/pkg/harfbuzz/include',
	'-isystem $builddir/pkg/fribidi/include',
	'-isystem $builddir/pkg/libffi/include',
	'-isystem $builddir/pkg/libxkbcommon/include',
	'-isystem $builddir/pkg/libepoxy/include',
	'-isystem $builddir/pkg/wayland/include',
	'-isystem $builddir/pkg/libevent/src',
	'-isystem $builddir/pkg/libevent/include',
	-- uxp/libjpeg exports (jpeglib.h etc. for the image decoders)
	'-isystem $builddir/pkg/uxp/libjpeg/include',
	'-isystem $builddir/pkg/linux-headers/include',
	'-I $builddir/pkg/glib/include/glib-2.0',
	'-I $builddir/pkg/glib/include/glib-2.0/glib',
	'-I $builddir/pkg/glib/include/glib-2.0/gobject',
	'-I $builddir/pkg/gio/include/glib-2.0',
	'-I $builddir/pkg/gio/include/glib-2.0/gio',
	'-I $builddir/pkg/gmodule/include/glib-2.0',
	'-I $builddir/pkg/pango/include/pango-1.0',
	'-I $builddir/pkg/gdk-pixbuf/include/gdk-pixbuf-2.0',
	'-I $builddir/pkg/gtk3/include/gtk-3.0',
	'-I $builddir/pkg/gtk3/gdk',
	'-I $builddir/pkg/gtk3/gtk',
	'-I $builddir/pkg/atk/include/atk-1.0',
	'-Wno-error=implicit-function-declaration',
	'-Wno-error=deprecated-declarations',
	'-Wno-error=unused-function',
	'-Wno-error=unused-variable',
	'-Wno-error=unused-parameter',
	'-Wno-error=sign-compare',
	'-Wno-error=comment',
	'-Wno-error=parentheses',
	'-Wno-error=switch',
	'-Wno-error=return-type',
	'-Wno-error=reorder',
	'-Wno-error=narrowing',
	'-Wno-error=format',
	'-Wno-error=class-memaccess',
	'-Wno-error=extra',
	'-Wno-error=ignored-qualifiers',
	'-Wno-error=pessimizing-move',
	'-Wno-error=sizeof-array-argument',
	'-Wno-error=varargs',
	'-Wno-error=incompatible-pointer-types',
	'-Wno-error=int-conversion',
}

-- ground-truth build defines (ACDEFINES committed as gen/defines.txt)
for line in iterlines('gen/defines.txt') do
	cflags{line}
end

local uxp = 'pkg/uxp/src/'

-- vendored include roots MUST precede the per-source-dir -I chain:
-- several (chromium/src) own a 'base/' dir whose headers shadow others;
-- the canonical root has to win
cflags{
	'-I $dir/gen/include/ipdl',
	-- NB: -I $dir/gen/include/mozilla/dom moved to the tail (after the
	-- source dirs): early, its TreeWalker.h/Connection.h shadow the tree's
	'-I $builddir/pkg/gtk3',
	'-I pkg/uxp/src/ipc/chromium/src',
	'-I pkg/uxp/src/intl/uconv/util',
	'-I pkg/uxp/src/hal/sandbox',
	'-I pkg/uxp/src/testing/gtest/mozilla',
	'-I pkg/uxp/src/uriloader/exthandler/unix',
	-- libevent: headers only (the chromium third-party unifies use them;
	-- the archive joins the link only if undefined refs appear)
	'-isystem $builddir/pkg/libevent/include',
}

-- dependency packages (headers installed by each pkg; archives join the
-- final link)
cflags{
	'-isystem $builddir/pkg/libvpx/include',
	'-isystem $builddir/pkg/libogg/include',
	'-isystem $builddir/pkg/libvorbis/include',
	'-isystem $builddir/pkg/libopus/include',
	'-isystem $builddir/pkg/libtheora/include',
	'-isystem $builddir/pkg/libwebp/include',
	'-isystem $builddir/pkg/brotli/include',
	'-isystem $builddir/pkg/woff2/include',
	'-isystem $builddir/pkg/graphite2/include',
	'-isystem $builddir/pkg/libsoundtouch/include',
	'-isystem $builddir/pkg/kissfft/include',
	'-isystem $builddir/pkg/libspeex/include',
	'-isystem $builddir/pkg/ots/include',
	'-isystem $builddir/pkg/libcubeb/include',
	'-isystem $builddir/pkg/nestegg/include',
	'-isystem $builddir/pkg/libjxl/include',
	'-isystem $builddir/pkg/libyuv/include',
	'-isystem $builddir/pkg/uxp/fdlibm/include',
	'-isystem $builddir/pkg/uxp/qcms/include',
	'-isystem $builddir/pkg/uxp/angle/include',
	'-isystem $builddir/pkg/uxp/libmkv/include',
	'-isystem $builddir/pkg/uxp/psshparser/include',
	'-isystem $builddir/pkg/uxp/libstagefright/include',
	'-isystem $builddir/pkg/uxp/protobuf/include',
}

-- skia stays inline (no standalone package)
cflags{
	'-I pkg/uxp/src/gfx/skia/skia/include/config',
	'-I pkg/uxp/src/gfx/skia/skia/include/core',
	'-I pkg/uxp/src/gfx/skia/skia/include/gpu',
	'-I pkg/uxp/src/gfx/skia/skia/include/utils',
	'-I pkg/uxp/src/gfx/skia/skia/include/effects',
	'-I pkg/uxp/src/gfx/skia/skia/include/pathops',
	'-I pkg/uxp/src/gfx/skia/skia/include/ports',
	'-I pkg/uxp/src/gfx/skia/skia/include/private',
	'-I pkg/uxp/src/gfx/skia/skia/include/images',
	'-I pkg/uxp/src/gfx/skia/skia/include/codec',
	'-I pkg/uxp/src/gfx/skia/skia/include/svg',
	'-I pkg/uxp/src/gfx/skia/skia/include/views',
	-- skia internal src dirs pulled in by unified members
	'-I pkg/uxp/src/gfx/skia/skia/src/sfnt',
	'-I pkg/uxp/src/gfx/skia/skia/src/lazy',
	-- gecko's HTTP compress conv reaches into brotli's internal dec/state.h
	'-I pkg/uxp/src/modules/brotli/dec',
	-- uconv converter tables live in ucvlatin (never compiled, headers only)
	'-I pkg/uxp/src/intl/uconv/ucvlatin',
	'-I pkg/uxp/src/intl/uconv/ucvja',
	'-I pkg/uxp/src/intl/uconv/ucvibm',
	'-I pkg/uxp/src/intl/uconv/ucvcn',
	'-I pkg/uxp/src/intl/uconv/ucvko',
	'-I pkg/uxp/src/intl/uconv/ucvtw',
}

-- every directory owning a compiled source (and every generated-header dir)
-- goes on the -I chain, replacing mozbuild's LOCAL_INCLUDES.
-- ORDER MATTERS: uxp tree dirs must precede the gen/include copies so a
-- tree header (accessible/base/TreeWalker.h) wins over the dist/include
-- copy of a DIFFERENT same-named header (mozilla/dom/TreeWalker.h); app
-- dirs follow, generated-header dirs last.
local sdirs = { uxp = {}, app = {}, hdr = {} }
for line in iterlines('gen/source-dirs.txt') do
	local kind, d = line:match('^(%w+):(.*)$')
	if kind then sdirs[kind][#sdirs[kind] + 1] = d end
end
for _, kind in ipairs({ 'uxp', 'app', 'hdr' }) do
	for _, d in ipairs(sdirs[kind]) do
	local root
	if kind == 'app' then root = '$srcdir/palemoon/'
	elseif kind == 'uxp' then root = uxp
	else root = '$dir/gen/include/' end
	-- dirs named 'base' would shadow the canonical roots above
	-- (accessible/base is whitelisted: its TreeWalker/FileUtils must
	-- beat the dist copies)
	if d ~= 'ipc/chromium/src/base' and not d:match('(^|/)base$')
		or d == 'accessible/base' then
		cflags{'-I ' .. root .. d}
	end
	end
end
-- top-level generated headers (xpidl nsIFoo.h, FileUtils.h, ...) come
-- AFTER the source dirs: gt resolved same-named headers to LOCAL_INCLUDES
-- copies first (FileLocation.h wants io's mozilla::AutoFDClose, not the
-- glue typedef that a top-level copy shadows)
cflags{'-I $dir/gen/include', '-I $dir/gen/include/mozilla/dom'}

-- pkg.deps MUST precede the object loops:
-- it is only wired into compiles issued while it is set, and the
-- exported-header consumers (heapsnapshot, layerscope, ...) have to order
-- after the packages' headers phonies (the T-079 cold-headers race)
pkg.deps = {
	'pkg/glib/headers',
	'pkg/gio/headers',
	'pkg/gmodule/headers',
	'pkg/pango/headers',
	'pkg/gdk-pixbuf/headers',
	'pkg/cairo/headers',
	'pkg/fribidi/headers',
	'pkg/harfbuzz/headers',
	'pkg/atk/headers',
	'pkg/wayland/headers',
	'pkg/wayland-protocols/headers',
	'pkg/libepoxy/headers',
	'pkg/libxkbcommon/headers',
	'pkg/libvpx/headers',
	'pkg/libogg/headers',
	'pkg/libvorbis/headers',
	'pkg/libopus/headers',
	'pkg/libtheora/headers',
	'pkg/libwebp/headers',
	'pkg/brotli/headers',
	'pkg/woff2/headers',
	'pkg/graphite2/headers',
	'pkg/libsoundtouch/headers',
	'pkg/kissfft/headers',
	'pkg/libspeex/headers',
	'pkg/ots/headers',
	'pkg/libcubeb/headers',
	'pkg/nestegg/headers',
	'pkg/libjxl/headers',
	'pkg/libyuv/headers',
	'pkg/uxp/fdlibm/headers',
	'pkg/uxp/qcms/headers',
	'pkg/uxp/angle/headers',
	'pkg/uxp/libmkv/headers',
	'pkg/uxp/psshparser/headers',
	'pkg/uxp/libstagefright/headers',
	'pkg/uxp/libjpeg/headers',
	'pkg/uxp/protobuf/headers',
	'pkg/libpng/headers',
	'pkg/zlib/headers',
	'pkg/libevent/headers',
	'pkg/nspr/headers',
	'pkg/nss/headers',
	'pkg/sqlite/headers',
	'pkg/libevent/headers',
	'pkg/linux-headers/headers',
	'pkg/uxp/fetch',
	'pkg/palemoon/fetch',
}

local objs = {}

-- include dirs for unified build files (their quoted includes name the
-- member sources, resolved against the real source directory)
local uidirs = {}
for line in iterlines('gen/uxp-objects.txt') do
	if line:match('^%$dir/gen/src/.*/Unified_') then
		local d = line:match('^%$dir/gen/src/(.*)/[^/]+$')
		if d then uidirs[d] = true end
	end
end
for d in pairs(uidirs) do
	cflags{'-I ' .. uxp .. d}
end

local function addobj(src, obj)
	local deps
	if pkg.deps then deps = '$gendir/deps' end
	-- per-file SIMD ISA flags (mozbuild SOURCES[...].flags equivalents)
	local extra
	if src:match('avx512') then
		extra = ' -mavx512f -mavx512cd -mavx512vl -mavx512dq -mavx512bw'
	elseif src:match('avx2') then
		extra = ' -mavx2'
	elseif src:match('_avx%.') or src:match('avx%.') then
		extra = ' -mavx'
	elseif src:match('ssse3') then
		extra = ' -mssse3'
	elseif src:match('sse4_1') or src:match('sse41') then
		extra = ' -msse4.1'
	elseif src:match('sse4_2') then
		extra = ' -msse4.2'
	end
	-- per-file exceptions to the gecko -fno-exceptions/-fno-rtti dialect
	-- (gt compiled these with rtti enabled; dynamic_cast is real here)
	local rtti = src:match('dom/u2f/Unified_cpp_dom_u2f0%.cpp$')
		or src:match('storage/Unified_cpp_storage0%.cpp$')
		or src:match('accessible/generic/HyperTextAccessible%.cpp$')
		or src:match('netwerk/build/nsNetModule%.cpp$')
		or src:match('gen/src/js/src/')
		or src:match('gfx/thebes/gfxPlatformGtk%.cpp$')
		or src:match('gen/src/toolkit/xre/Unified_cpp_toolkit_xre0%.cpp$')
		-- the Runnable key-function TU: emits the typeinfo the rtti
		-- opt-out objects reference
		or src:match('xpcom/threads/nsThreadUtils%.cpp$')
		or src:match('dom/heapsnapshot/CoreDump%.pb%.[ch]%a*$')
		or src:match('gen/src/gfx/layers/Unified_cpp_gfx_layers6%.cpp$')
		or src:match('gen/src/gfx/layers/Unified_cpp_gfx_layers7%.cpp$')
	if rtti then extra = (extra or '') .. ' -frtti -fexceptions' end
	-- spidermonkey: the build force-includes js-confdefs.h and carries its
	-- own backend defines (gt js/src/backend.mk); without these the
	-- trace-logging and wasm-signal paths break
	if src:match('gen/src/js/src/') or src:match('uxp/src/js/src/') then
		extra = (extra or '')
			.. ' -include $dir/gen/include/js/src/js-confdefs.h'
			.. ' -D MOZ_HAS_MOZGLUE -D ENABLE_SHARED_ARRAY_BUFFER'
			.. ' -D EXPORT_JS_API -D ENABLE_BINARYDATA -D ENABLE_SIMD'
			.. ' -D JS_HAS_CTYPES -D FFI_BUILDING'
	end
	-- external-API code: gt compiled these without MOZILLA_INTERNAL_API
	-- (nsStringAPI users); the xpcom/glue objects provide that API
	local extapi = src:match('gen/src/xpcom/glue/')
		or src:match('palemoon/components/build/nsModule%.cpp$')
		or src:match('palemoon/components/dirprovider/')
		or src:match('palemoon/components/feeds/')
		or src:match('palemoon/components/shell/')
	if extapi then extra = (extra or '') .. ' -U MOZILLA_INTERNAL_API' end
	-- the launcher is a glue client (XRE_* decls live behind XPCOM_GLUE)
	if src:match('palemoon/app/nsBrowserApp%.cpp$') then
		extra = (extra or '')
			.. ' -D XPCOM_GLUE -U MOZILLA_INTERNAL_API'
	end
	local cf
	if deps then cf = {src, '||', deps} else cf = src end
	local args
	if extra then args = {cflags = '$cflags' .. extra} end
	build('cc', obj, cf, args)
	objs[#objs + 1] = obj
end

for line in iterlines('gen/uxp-objects.txt') do
	local src, base
	if line:sub(1, 1) == '$' then
		src = line
		base = line:gsub('^%$dir/gen/src/', 'gen/src/')
	else
		src = uxp .. line
		base = 'uxp/' .. line
	end
	if not src:match('%.s$') and not src:match('%.asm$') then
		addobj(src, '$outdir/' .. base .. '.o')
	end
end
for line in iterlines('gen/app-objects.txt') do
	local src, base
	if line:sub(1, 1) == '$' then
		src = line
		base = line:gsub('^%$dir/gen/src/', 'gen/src/')
	else
		src = '$srcdir/palemoon/' .. line
		base = 'app/' .. line
	end
	if not src:match('%.s$') and not src:match('%.asm$') then
		addobj(src, '$outdir/' .. base .. '.o')
	end
end


objs[#objs + 1] = '$builddir/pkg/libvpx/libvpx.a'
objs[#objs + 1] = '$builddir/pkg/libogg/libogg.a'
objs[#objs + 1] = '$builddir/pkg/libvorbis/libvorbis.a'
objs[#objs + 1] = '$builddir/pkg/libopus/libopus.a'
objs[#objs + 1] = '$builddir/pkg/libtheora/libtheora.a'
objs[#objs + 1] = '$builddir/pkg/libwebp/libwebp.a'
objs[#objs + 1] = '$builddir/pkg/brotli/libbrotli.a'
objs[#objs + 1] = '$builddir/pkg/woff2/libwoff2.a'
objs[#objs + 1] = '$builddir/pkg/graphite2/libgraphite2.a'
objs[#objs + 1] = '$builddir/pkg/libsoundtouch/libsoundtouch.a'
objs[#objs + 1] = '$builddir/pkg/kissfft/libkissfft.a'
objs[#objs + 1] = '$builddir/pkg/libspeex/libspeex.a'
objs[#objs + 1] = '$builddir/pkg/ots/libots.a'
objs[#objs + 1] = '$builddir/pkg/libcubeb/liblibcubeb.a'
objs[#objs + 1] = '$builddir/pkg/nestegg/libnestegg.a'
objs[#objs + 1] = '$builddir/pkg/libjxl/libjxl.a'
objs[#objs + 1] = '$builddir/pkg/libjxl/libhwy.a'
objs[#objs + 1] = '$builddir/pkg/libyuv/liblibyuv.a'
objs[#objs + 1] = '$builddir/pkg/uxp/fdlibm/libfdlibm.a'
objs[#objs + 1] = '$builddir/pkg/uxp/qcms/libqcms.a'
objs[#objs + 1] = '$builddir/pkg/uxp/angle/libangle.a'
objs[#objs + 1] = '$builddir/pkg/uxp/libmkv/libmkv.a'
objs[#objs + 1] = '$builddir/pkg/uxp/psshparser/libpsshparser.a'
objs[#objs + 1] = '$builddir/pkg/uxp/libstagefright/libstagefright.a'
objs[#objs + 1] = '$builddir/pkg/uxp/protobuf/libprotobuf.a'
ar('libpalemoon.a', objs)

-- T-070: the static PIE link. Everything goes on the link line inside one
-- group (-Wl,--start-group/--end-group spans $in and $ldlibs): the gecko
-- <-> nspr/nss and glib <-> gio circularities need it, and unreferenced
-- members cost nothing.
local linklibs = {
	'$outdir/libpalemoon.a',
	-- the uxp sub-package archives (the media/codec stack)
	'$builddir/pkg/libvpx/libvpx.a',
	'$builddir/pkg/libogg/libogg.a',
	'$builddir/pkg/libvorbis/libvorbis.a',
	'$builddir/pkg/libopus/libopus.a',
	'$builddir/pkg/libtheora/libtheora.a',
	'$builddir/pkg/libwebp/libwebp.a',
	'$builddir/pkg/brotli/libbrotli.a',
	'$builddir/pkg/woff2/libwoff2.a',
	'$builddir/pkg/graphite2/libgraphite2.a',
	'$builddir/pkg/libsoundtouch/libsoundtouch.a',
	'$builddir/pkg/kissfft/libkissfft.a',
	'$builddir/pkg/libspeex/libspeex.a',
	'$builddir/pkg/ots/libots.a',
	'$builddir/pkg/libcubeb/liblibcubeb.a',
	'$builddir/pkg/nestegg/libnestegg.a',
	'$builddir/pkg/libjxl/libjxl.a',
	'$builddir/pkg/libjxl/libhwy.a',
	'$builddir/pkg/libyuv/liblibyuv.a',
	'$builddir/pkg/uxp/fdlibm/libfdlibm.a',
	'$builddir/pkg/uxp/qcms/libqcms.a',
	'$builddir/pkg/uxp/angle/libangle.a',
	'$builddir/pkg/uxp/libmkv/libmkv.a',
	'$builddir/pkg/uxp/psshparser/libpsshparser.a',
	'$builddir/pkg/uxp/libstagefright/libstagefright.a',
	'$builddir/pkg/uxp/protobuf/libprotobuf.a',
	-- the gtk/core stack
	'$builddir/pkg/nspr/libnspr.a',
	'$builddir/pkg/nss/libnss.a',
	'$builddir/pkg/nss/libnssutil.a',
	'$builddir/pkg/nss/libssl.a',
	'$builddir/pkg/nss/libsmime.a',
	'$builddir/pkg/nss/libcrmf.a',
	'$builddir/pkg/nss/libmozpkix.a',
	'$builddir/pkg/nss/libfreebl.a',
	'$builddir/pkg/nss/libsoftokn.a',
	'$builddir/pkg/sqlite/libsqlite3.a',
	'$builddir/pkg/icu/libicui18n.a',
	'$builddir/pkg/icu/libicuuc.a',
	'$builddir/pkg/icu/libicudata.a',
	'$builddir/pkg/glib/libglib-2.0.a',
	'$builddir/pkg/glib/libgobject-2.0.a',
	'$builddir/pkg/gio/libgio-2.0.a',
	'$builddir/pkg/gmodule/libgmodule-2.0.a',
	'$builddir/pkg/gtk3/libgtk-3.a',
	'$builddir/pkg/gdk-pixbuf/libgdk_pixbuf-2.0.a',
	'$builddir/pkg/atk/libatk-1.0.a',
	'$builddir/pkg/pango/libpango-1.0.a',
	'$builddir/pkg/cairo/libcairo.a',
	'$builddir/pkg/pixman/libpixman.a',
	'$builddir/pkg/freetype/libfreetype.a',
	'$builddir/pkg/harfbuzz/libharfbuzz.a',
	'$builddir/pkg/fribidi/libfribidi.a',
	'$builddir/pkg/nspr/libplc4.a',
	'$builddir/pkg/nspr/libplds4.a',
	'$builddir/pkg/fontconfig/libfontconfig.a',
	'$builddir/pkg/expat/libexpat.a',
	'$builddir/pkg/libpng/libpng.a',
	'$builddir/pkg/zlib/libz.a',
	'$builddir/pkg/libffi/libffi.a',
	'$builddir/pkg/wayland/libwayland-client.a',
	'$builddir/pkg/wayland/libwayland-cursor.a',
	'$builddir/pkg/wayland/libwayland-egl.a',
	'$builddir/pkg/libxkbcommon/libxkbcommon.a',
	'$builddir/pkg/libepoxy/libepoxy.a',
	'$builddir/pkg/alsa-lib/libasound.a',
	'$builddir/pkg/util-linux/libuuid.a',
	'$builddir/pkg/util-linux/libcommon.a',
	'$builddir/pkg/openbsd/libbsd.a',
	'$builddir/pkg/libevent/libevent.a',
}
exe('omoon', linklibs, nil, {
	ldflags = '$ldflags -Wl,--start-group',
	ldlibs = '-Wl,--end-group -lstdc++ -Wl,-z,notext',
})

fetch 'git'
